import { useMemo, useState } from 'react'
import { useAuth } from '../App'

export default function CompleteInvitePage() {
  const { api, refreshAuth } = useAuth()
  const token = useMemo(() => new URLSearchParams(window.location.search).get('token') || '', [])
  const [password, setPassword] = useState('')
  const [confirmPassword, setConfirmPassword] = useState('')
  const [loading, setLoading] = useState(false)
  const [message, setMessage] = useState('')
  const [success, setSuccess] = useState(false)

  async function handleSubmit(event) {
    event.preventDefault()
    setMessage('')

    if (!token) {
      setMessage('Invite token is missing from this link.')
      return
    }

    if (password.length < 8) {
      setMessage('Password must be at least 8 characters.')
      return
    }

    if (password !== confirmPassword) {
      setMessage('Passwords do not match.')
      return
    }

    setLoading(true)
    try {
      await api.post('/auth/complete-invite', { token, password })
      await refreshAuth()
      setSuccess(true)
      setMessage('Invite completed successfully. Redirecting into the workspace...')
      window.history.replaceState({}, '', '/')
    } catch (error) {
      setMessage(error.message)
    } finally {
      setLoading(false)
    }
  }

  return (
    <div style={shellStyle}>
      <style>{pageStyles}</style>
      <div style={orbStyle('10%', 'auto', '#2be3b4', '8%')} />
      <div style={orbStyle('56%', '8%', '#ff8552')} />
      <div style={orbStyle('auto', '36%', '#6dc6ff', '66%', 'auto', '20%')} />

      <div style={frameStyle} className="invite-grid">
        <section style={heroStyle}>
          <div style={eyebrowStyle}>Operator Invite</div>
          <div style={titleStyle}>Activate your DALA WMS access and set a secure password.</div>
          <div style={copyStyle}>
            This link was generated by an administrator. Complete setup once, then use your email and password on the live Railway deployment at `dalawms.up.railway.app`.
          </div>
        </section>

        <section style={panelStyle}>
          <div style={wordmarkStyle}>DALA <span style={{ color: '#2be3b4' }}>WMS</span></div>
          <div style={subtitleStyle}>Complete invite</div>
          <div style={noticeStyle}>
            Password must be at least 8 characters and should be rotated if it was shared insecurely.
          </div>

          <form onSubmit={handleSubmit}>
            <Field label="New Password">
              <input type="password" value={password} onChange={(event) => setPassword(event.target.value)} required style={inputStyle} />
            </Field>
            <Field label="Confirm Password">
              <input type="password" value={confirmPassword} onChange={(event) => setConfirmPassword(event.target.value)} required style={inputStyle} />
            </Field>

            {message && (
              <div style={{
                ...messageStyle,
                borderColor: success ? 'rgba(43, 227, 180, 0.22)' : 'rgba(255, 133, 82, 0.22)',
                color: success ? '#8df1cf' : '#ffb191',
                background: success ? 'rgba(43,227,180,0.09)' : 'rgba(255,133,82,0.09)',
              }}>
                {message}
              </div>
            )}

            <button type="submit" disabled={loading} style={buttonStyle}>
              {loading ? 'Please wait...' : 'Activate Access'}
            </button>
          </form>
        </section>
      </div>
    </div>
  )
}

function Field({ label, children }) {
  return (
    <div style={{ marginBottom: 16 }}>
      <label style={labelStyle}>{label}</label>
      {children}
    </div>
  )
}

function orbStyle(top, right, color, left = 'auto', bottom = 'auto', size = '22%') {
  return {
    position: 'fixed',
    top,
    right,
    left,
    bottom,
    width: size,
    aspectRatio: '1 / 1',
    borderRadius: '50%',
    background: `radial-gradient(circle, ${color}26 0%, transparent 68%)`,
    filter: 'blur(24px)',
    pointerEvents: 'none',
  }
}

const shellStyle = {
  minHeight: '100vh',
  display: 'grid',
  placeItems: 'center',
  padding: '28px 18px',
  background: '#071012',
  position: 'relative',
  overflow: 'hidden',
}

const frameStyle = {
  width: '100%',
  maxWidth: 1100,
  display: 'grid',
  gridTemplateColumns: '1fr 0.95fr',
  gap: 22,
  position: 'relative',
  zIndex: 1,
}

const heroStyle = {
  borderRadius: 28,
  padding: '38px 34px',
  border: '1px solid rgba(126, 155, 160, 0.12)',
  background: 'linear-gradient(180deg, rgba(11,22,24,0.94) 0%, rgba(7,14,16,0.96) 100%)',
  boxShadow: '0 28px 80px rgba(0,0,0,0.26)',
}

const panelStyle = {
  borderRadius: 28,
  padding: '34px 30px',
  border: '1px solid rgba(126, 155, 160, 0.12)',
  background: 'linear-gradient(180deg, rgba(17,29,32,0.96) 0%, rgba(8,16,18,0.98) 100%)',
  boxShadow: '0 24px 72px rgba(0,0,0,0.3)',
}

const eyebrowStyle = {
  fontFamily: 'DM Mono, monospace',
  fontSize: 10,
  letterSpacing: '0.18em',
  textTransform: 'uppercase',
  color: '#6f858d',
  marginBottom: 18,
}

const titleStyle = {
  fontFamily: 'Syne, sans-serif',
  fontWeight: 800,
  fontSize: 42,
  lineHeight: 1,
  letterSpacing: '-0.05em',
  color: '#f6fbf9',
}

const copyStyle = {
  marginTop: 18,
  color: '#9bb0b4',
  fontSize: 15,
  lineHeight: 1.7,
}

const wordmarkStyle = {
  fontFamily: 'Syne, sans-serif',
  fontWeight: 800,
  fontSize: 34,
  letterSpacing: '-0.05em',
  color: '#f5fbf8',
}

const subtitleStyle = {
  fontFamily: 'DM Mono, monospace',
  fontSize: 10,
  letterSpacing: '0.18em',
  color: '#6f858d',
  textTransform: 'uppercase',
  marginTop: 4,
}

const noticeStyle = {
  marginTop: 24,
  marginBottom: 18,
  padding: '12px 14px',
  borderRadius: 14,
  border: '1px solid rgba(109, 198, 255, 0.2)',
  background: 'rgba(109, 198, 255, 0.08)',
  color: '#8fd8ff',
  fontSize: 13,
  lineHeight: 1.6,
}

const labelStyle = {
  display: 'block',
  fontFamily: 'DM Mono, monospace',
  fontSize: 10,
  letterSpacing: '0.16em',
  color: '#6f858d',
  textTransform: 'uppercase',
  marginBottom: 8,
}

const inputStyle = {
  width: '100%',
  padding: '13px 14px',
  borderRadius: 16,
  border: '1px solid rgba(126, 155, 160, 0.14)',
  background: 'rgba(4,9,10,0.7)',
  color: '#eef6f4',
  fontFamily: 'DM Sans, sans-serif',
  fontSize: 14,
}

const messageStyle = {
  marginBottom: 16,
  borderRadius: 16,
  border: '1px solid',
  padding: '13px 14px',
  fontSize: 13,
  lineHeight: 1.5,
}

const buttonStyle = {
  width: '100%',
  padding: '14px 16px',
  border: '1px solid rgba(43, 227, 180, 0.36)',
  borderRadius: 18,
  background: 'linear-gradient(135deg, #2be3b4 0%, #7bffdb 100%)',
  color: '#04110f',
  cursor: 'pointer',
  fontFamily: 'Syne, sans-serif',
  fontWeight: 800,
  fontSize: 15,
  letterSpacing: '-0.02em',
  boxShadow: '0 16px 34px rgba(43, 227, 180, 0.18)',
}

const pageStyles = `
  @import url('https://fonts.googleapis.com/css2?family=Syne:wght@400;600;700;800&family=DM+Sans:wght@300;400;500;600;700&family=DM+Mono:wght@400;500&display=swap');

  * { box-sizing: border-box; margin: 0; padding: 0; }

  input:focus {
    outline: none;
    border-color: #2be3b4 !important;
    box-shadow: 0 0 0 4px rgba(43, 227, 180, 0.08);
  }

  @media (max-width: 960px) {
    .invite-grid {
      grid-template-columns: 1fr;
    }
  }
`
